[package]
name = "openxet-cas-types"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
xet-core-structures = { workspace = true }
xet-data = { workspace = true }
reqwest = { version = "0.12", features = ["blocking"] }
